### ISSUE TITLE
Isorec TWRP can't mount usb storage on DorimanX

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/initramfs3#15]
**Project commencement:** January 27th 2016

**Project Status:** Solved

**Things to do:** Nothing left to do

**ETA:** Completed.

**Comment by arny24x7** [comment]
It can't be selinux as twrp force runs itself in permissive mode with a script. Can u plz provide me a last_ksmg after re-creating this problem.

**Comment by gsstudios** [comment]
Seems to be fine on the latest build (12.0 b002). Looks like a bad driver was the culprit to my problems :)
