### ISSUE TITLE
mDNIE Control

### ISSUE THREAD

**Issue by chhapil** [gsstudios/initramfs3#25]
I think there is a way to add mDNIE tuning to CM12. the current color or adaptive color is too dark and vivid my taste. It would be possible to set the modes.
I was using CM LP nightly for a while and then all havoc got lose on my phone so back to JB now
May be you can try. 
I'm asking lot of things to you these days :(

http://forum.xda-developers.com/galaxy-s2/help/qa-cyanogenmod-12-t2955591/page77

the older color control revert in Dorimanx
https://github.com/chhapil/initramfs3/commit/2f2034987d537a52662be4389edba8144d960ffd

**Comment by gsstudios** [comment]
I was experimenting with this on KK, but I guess I didn't play around with it enough. Will see if anything can be done.

**Comment by chhapil** [comment]
Cool, we don't need this change on JB because ROM already has the controls.

**Comment by gsstudios** [comment]
I think this commit is also important for colour change support: https://github.com/gsstudios/Dorimanx-SG2-I9100-Kernel/commit/3c0539b6729e2137b7c457afc3ac2f9dbf08f539

**Comment by gsstudios** [comment]
Mdnie scenario/profile changing is simple, is available for almost all android versions, however tuning the colour will absolutely not work on newer android versions. 

Also, if you want to add this, stock ROMs mdnie values are different. You will have to check for yourself.

**Comment by gsstudios** [comment]
Initial support for mdnie mode and scenario tweaking: https://github.com/gsstudios/initramfs3/commit/d4a33b78851fe6ad6bec0b39b9052751df8bd5c6 Using existing scripts to set the values. A new script will have to be made to allow/block overwrite of ROMs mdnie value.

**Comment by gsstudios** [comment]
Proper solution here: https://github.com/gsstudios/initramfs3/commit/0b91251264750e38f741bbccda0b3fb538641382

Users may have to re-enable the override toggle if their settings don't apply properly. Not a bug but it is  just what users have to do.

**Comment by gsstudios** [comment]
https://github.com/gsstudios/initramfs3/commit/7b0fb94f779229f9365cafe5143ee797c46b9108

Just in-case user ask why their settings are not applying.

**Comment by gsstudios** [comment]
I don't know why this is still open. Closed :)
