### ISSUE TITLE
RESURRECTION REMIX LP FCs

### ISSUE THREAD

**Issue by gsstudios** [gsstudios/initramfs3#36]
According to reports on XDA, RR LP seems to be experiencing FCs when you open any app. I haven't confirmed this for myself but I will see if I can solve it. 

**Status:** Not started yet

**ETA:** Unknown

**Comment by gsstudios** [comment]
@Realex-fire

Here is a logcat kindly provided by lightmandn:
https://yadi.sk/i/LdNU0i04t9uUq

**Comment by Realex-fire** [comment]
Quite expected error, RR for some reason doesn't want to read libraries of new mali driver, this error can be solved only release of the separate version.

```
E/libEGL (19782): load_driver(/system/lib/egl/libEGL_mali.so): dlopen failed: library "/system/lib/egl/libEGL_mali.so" not found

F/libEGL (19782): couldn't find an OpenGL ES implementation

F/libc (19782): Fatal signal 4 (SIGILL), code 1, fault addr 0xb6e3090e in tid 19804 (RenderThread)
```

EDIT: Now we have implemented support for only the cyanogenmod, everything else can work improperly.

**Comment by gsstudios** [comment]
Yeah, I'll probably just support CM ROMs from now on.
